options:
  app_name:
    type: string
    default: mongonode-app
    description: Application Name
  app_port:
    type: int
    default: 8000
    description: Port where the application will handle requests
  app_scm:
    type: string
    default: git
    description: Repository type (git/bzr/...)
  app_url:
    type: string
    default: "http://github.com/TheMindCompany/mongonode-app.git"
    description: Application repository URL
  app_branch:
    type: string
    default: master
    description: Application repository deployment branch. Might also be a revision ID (e.g. tag or SHA1 for git) to upgrade/downgrade application.
  polling_schedule:
    type: string
    default: ""
    description: Set to a cron schedule string (e.g. "*/5 * * * *" poll each 5 minutes) for polling repo for updates and deploy if new branch contents is found. Set to empty to disable polling.
  install_root:
    type: string
    default: /opt
    description: Install the application in app_name under this directory
  app_user:
    type: string
    default: ubuntu
    description: run-as user
  app_node_env:
    type: string
    default: production
    description: The node environment to run as ("production", "development", "test" etc.).
